# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Votic spellchecker"
vot = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Votic, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
vot = "TRANSLATE: A spellchecker for Votic, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.vot"

[windows]
system_product_code = "{C899A99C-0A32-45B3-BB8C-883FC5269CE4}_is1"

[package.speller]
name = "Votic"
version = "0.1.0"

[package.grammar]
name = "Votic"
version = "0.1.0"

[package.tts-text-proc]
name = "Votic"
version = "0.1.0"

[package.hyphenator]
name = "__UNDEFINED__"
version = "0.1.0"
